const $=s=>document.querySelector(s),app=$('#app');
let bank=[],activeQuiz=null,currentIndex=0,answers={},confidence={},checked={},mode='study',route='home';
const D={attempts:[],missed:[],favorites:[],theme:'light',topicStats:{}};
const state=Object.assign({},D,JSON.parse(localStorage.getItem('rmaStateV11')||'{}'));
document.documentElement.dataset.theme=state.theme;
function save(){localStorage.setItem('rmaStateV11',JSON.stringify(state))}
function go(r){route=r;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render();scrollTo(0,0)}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.route));
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save()};
const sh=a=>[...a].sort(()=>Math.random()-.5),pct=(n,d)=>d?Math.round(n/d*100):0;
async function init(){try{bank=await fetch('questions-general.json').then(r=>r.json())}catch(e){app.innerHTML='<section class="card warning"><h2>Question bank could not load</h2><p>Refresh the hosted website after GitHub Pages finishes deploying.</p></section>';return}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function render(){({home,study,quiz:quizMenu,saved,progress}[route]||home)()}
function home(){let best=state.attempts.length?Math.max(...state.attempts.map(a=>a.score)):0,total=state.attempts.reduce((s,a)=>s+a.total,0);app.innerHTML=`<section class="hero"><h1>Learn. Practice. Succeed.</h1><span class="version-chip">Version 1.1</span><p>All 65 General Medical Assisting questions with answer-by-answer explanations.</p></section><section class="grid"><article class="card card-button" onclick="startQuiz(65,'exam')"><span class="badge">Work Area I</span><h2>65-Question Exam</h2><p>Complete General Medical Assisting in Exam Mode.</p></article><article class="card card-button" onclick="go('study')"><span class="badge">Study Mode</span><h2>Study by Topic</h2><p>Check each answer, read explanations, and save difficult questions.</p></article><article class="card card-button" onclick="go('quiz')"><h2>Quick Quiz</h2><p>Choose 10, 25, 50, or 65 questions.</p></article><article class="card"><span class="badge">Coming next</span><h2>Work Area II</h2><p>Administrative Medical Assisting — 30 questions.</p></article></section><section class="grid"><article class="card"><div class="muted">Questions answered</div><div class="stat">${total}</div></article><article class="card"><div class="muted">Best score</div><div class="stat">${best}%</div></article><article class="card"><div class="muted">Favorites</div><div class="stat">${state.favorites.length}</div></article><article class="card"><div class="muted">Missed bank</div><div class="stat">${state.missed.length}</div></article></section>`}
function study(){let topics=[...new Set(bank.map(q=>q.topic))];app.innerHTML=`<h1>Study by Topic</h1><p class="muted">Choose an answer, then tap Check Answer for a complete explanation.</p><section class="card">${topics.map(t=>`<div class="topic-row"><span><strong>${t}</strong><br><span class="small muted">${bank.filter(q=>q.topic===t).length} questions</span></span><button class="btn btn-secondary" onclick='startTopic(${JSON.stringify(t)})'>Study</button></div>`).join('')}</section>`}
function quizMenu(){app.innerHTML=`<h1>Quick Quiz</h1><div class="pill-row"><button class="pill ${mode==='study'?'active':''}" onclick="setMode('study')">Study Mode</button><button class="pill ${mode==='exam'?'active':''}" onclick="setMode('exam')">Exam Mode</button></div><section class="grid">${[10,25,50,65].map(n=>`<article class="card card-button" onclick="startQuiz(${n},mode)"><h2>${n} Questions</h2><p>${n===65?'Full Work Area I':'Randomized practice'}</p></article>`).join('')}</section>`}
window.setMode=m=>{mode=m;quizMenu()};
window.startQuiz=(n,m='study')=>{mode=m;activeQuiz=sh(bank).slice(0,Math.min(n,bank.length));currentIndex=0;answers={};confidence={};checked={};showQ()};
window.startTopic=t=>{mode='study';activeQuiz=sh(bank.filter(q=>q.topic===t));currentIndex=0;answers={};confidence={};checked={};showQ()};
function explain(q,c){let ok=c===q.a;return `<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Correct':'Not quite'}</strong><br>${ok?'':`Correct answer: ${'ABCD'[q.a]}. ${q.choices[q.a]}<br>`}${q.exp}</div><div class="option-review"><strong>Why each option is right or wrong:</strong>${q.choices.map((x,i)=>`<div class="option-note ${i===q.a?'correct-option':''}"><strong>${'ABCD'[i]}. ${x}</strong><br>${q.optionExplanations[i]}</div>`).join('')}</div><div class="tip"><strong>💡 Remember:</strong> ${q.tip}</div>`}
function showQ(){let q=activeQuiz[currentIndex],c=answers[q.id],fav=state.favorites.includes(q.id),cf=confidence[q.id],done=checked[q.id];app.innerHTML=`<section class="card"><button class="star" onclick="toggleFav('${q.id}')">${fav?'★':'☆'}</button><div class="question-head"><span>Question ${currentIndex+1} of ${activeQuiz.length}</span><span>${q.topic} • ${q.difficulty}</span></div><div class="progress-track" style="margin:12px 0 20px"><div class="progress-fill" style="width:${(currentIndex+1)/activeQuiz.length*100}%"></div></div><h2>${q.q}</h2>${q.choices.map((x,i)=>`<label class="choice"><input type="radio" name="ans" value="${i}" ${c===i?'checked':''} ${done&&mode==='study'?'disabled':''}><strong>${'ABCD'[i]}.</strong> ${x}</label>`).join('')}${mode==='study'&&!done?'<button class="btn btn-primary" onclick="checkAnswer()">Check Answer</button>':''}${mode==='study'&&done?explain(q,c):''}<div class="confidence"><button class="${cf==='high'?'active':''}" onclick="setConf('${q.id}','high')">😊 Confident</button><button class="${cf==='medium'?'active':''}" onclick="setConf('${q.id}','medium')">😐 Unsure</button><button class="${cf==='guess'?'active':''}" onclick="setConf('${q.id}','guess')">😬 Guessed</button></div><div class="btn-row"><button class="btn btn-secondary" onclick="prevQ()" ${currentIndex===0?'disabled':''}>Previous</button><button class="btn btn-primary" onclick="${currentIndex===activeQuiz.length-1?'finishQuiz()':'nextQ()'}">${currentIndex===activeQuiz.length-1?'Submit':'Next'}</button><button class="btn btn-secondary" onclick="go('home')">Exit</button></div></section>`;document.querySelectorAll('input[name=ans]').forEach(i=>i.onchange=()=>answers[q.id]=+i.value)}
window.checkAnswer=()=>{let q=activeQuiz[currentIndex];if(answers[q.id]===undefined){alert('Choose an answer first.');return}checked[q.id]=true;showQ()};
window.setConf=(id,v)=>{confidence[id]=v;showQ()};window.toggleFav=id=>{state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();showQ()};
window.nextQ=()=>{currentIndex++;showQ()};window.prevQ=()=>{currentIndex--;showQ()};
window.finishQuiz=()=>{let correct=0,details=activeQuiz.map(q=>{let c=answers[q.id],ok=c===q.a;if(ok)correct++;else if(!state.missed.includes(q.id))state.missed.push(q.id);let s=state.topicStats[q.topic]||{correct:0,total:0};s.total++;if(ok)s.correct++;state.topicStats[q.topic]=s;return{q,c,ok}}),score=Math.round(correct/activeQuiz.length*100);state.attempts.push({date:new Date().toISOString(),score,correct,total:activeQuiz.length,mode});save();app.innerHTML=`<section class="hero center"><h1>${score}%</h1><p>${correct} of ${activeQuiz.length} correct</p></section><div class="btn-row"><button class="btn btn-primary" onclick="go('home')">Home</button><button class="btn btn-secondary" onclick="go('saved')">Review Saved</button></div><h2>Answer Review</h2>${details.map((d,i)=>`<section class="card"><div class="question-head"><span>Question ${i+1}</span><span>${d.q.topic}</span></div><h3>${d.q.q}</h3>${explain(d.q,d.c)}</section>`).join('')}`;activeQuiz=null};
function saved(){let favs=state.favorites.map(id=>bank.find(q=>q.id===id)).filter(Boolean),missed=state.missed.map(id=>bank.find(q=>q.id===id)).filter(Boolean);app.innerHTML=`<h1>Saved Review</h1><section class="grid"><article class="card"><h2>⭐ Favorites</h2><p>${favs.length} saved</p>${favs.length?'<button class="btn btn-primary" onclick="startCustom(\'favorites\')">Practice Favorites</button>':''}</article><article class="card"><h2>❌ Missed</h2><p>${missed.length} to review</p>${missed.length?'<button class="btn btn-primary" onclick="startCustom(\'missed\')">Practice Missed</button>':''}</article></section>${favs.map(q=>`<section class="card"><span class="badge">${q.topic}</span><h3>${q.q}</h3><p><strong>Correct:</strong> ${'ABCD'[q.a]}. ${q.choices[q.a]}</p><div class="tip">${q.tip}</div><div class="mastered-row"><span class="small muted">Finished reviewing?</span><button class="btn btn-secondary" onclick="markMastered('${q.id}')">Mark Mastered</button></div></section>`).join('')}`}
window.markMastered=id=>{state.favorites=state.favorites.filter(x=>x!==id);state.missed=state.missed.filter(x=>x!==id);save();saved()};
window.startCustom=type=>{let ids=type==='favorites'?state.favorites:state.missed;activeQuiz=sh(ids.map(id=>bank.find(q=>q.id===id)).filter(Boolean));mode='study';currentIndex=0;answers={};confidence={};checked={};showQ()};
function progress(){let a=state.attempts,avg=a.length?Math.round(a.reduce((x,y)=>x+y.score,0)/a.length):0,best=a.length?Math.max(...a.map(x=>x.score)):0,rows=Object.entries(state.topicStats).map(([t,s])=>`<tr><td>${t}</td><td>${s.correct}/${s.total}</td><td>${pct(s.correct,s.total)}%</td></tr>`).join('');app.innerHTML=`<h1>Progress</h1><section class="grid"><article class="card"><div class="muted">Attempts</div><div class="stat">${a.length}</div></article><article class="card"><div class="muted">Average</div><div class="stat">${avg}%</div></article><article class="card"><div class="muted">Best</div><div class="stat">${best}%</div></article><article class="card"><div class="muted">Favorites</div><div class="stat">${state.favorites.length}</div></article></section><section class="card" style="margin-top:18px"><h2>Performance by Topic</h2>${rows?`<table><thead><tr><th>Topic</th><th>Correct</th><th>Score</th></tr></thead><tbody>${rows}</tbody></table>`:'<p class="muted">Complete a quiz to begin tracking.</p>'}</section>`}
init();