const $=s=>document.querySelector(s),app=$('#app');let bank=[],activeQuiz=null,currentIndex=0,answers={},route='home';
const state=JSON.parse(localStorage.getItem('rmaState')||'{"attempts":[],"missed":[],"theme":"light"}');document.documentElement.dataset.theme=state.theme;
function save(){localStorage.setItem('rmaState',JSON.stringify(state))}function go(r){route=r;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render();scrollTo(0,0)}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.route));$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save()};
async function init(){try{bank=await fetch('data/questions-general.json').then(r=>r.json())}catch(e){app.innerHTML='<section class="card warning"><h2>Open this as a hosted website</h2><p>The phone blocked the question file. Upload the entire folder to GitHub Pages, Netlify, or Cloudflare Pages, then open the web address.</p></section>';return}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function render(){({home,study,quiz:quizMenu,missed,progress}[route]||home)()}
function home(){let last=state.attempts.at(-1);app.innerHTML=`<section class="hero"><h1>Learn. Practice. Succeed.</h1><p>Original RMA study questions, explanations, and progress tracking.</p></section><section class="grid">
<article class="card card-button" onclick="startQuiz(65)"><span class="badge">Available now</span><h2>Work Area I</h2><p>General Medical Assisting — 65-question practice exam.</p></article>
<article class="card"><span class="badge">Coming next</span><h2>Work Area II</h2><p>Administrative Medical Assisting — 30 questions.</p></article>
<article class="card"><span class="badge">Coming next</span><h2>Work Area III</h2><p>Clinical Medical Assisting — 115 questions.</p></article>
<article class="card card-button" onclick="go('quiz')"><h2>Quick Quiz</h2><p>Choose 10, 25, or 50 questions.</p></article></section>
<section class="card" style="margin-top:18px"><h2>Your latest result</h2>${last?`<div class="stat">${last.score}%</div><p class="muted">${last.correct} of ${last.total} correct</p>`:'<p class="muted">Complete your first quiz to begin tracking progress.</p>'}</section>
<section class="card warning" style="margin-top:18px"><strong>Notice:</strong> Independent study resource; not an official AMT product and not made from real AMT exam questions.</section>`}
function study(){let topics=[...new Set(bank.map(q=>q.topic))];app.innerHTML=`<h1>Study by Topic</h1><section class="card">${topics.map(t=>`<div class="topic-row"><span><strong>${t}</strong><br><span class="small muted">${bank.filter(q=>q.topic===t).length} questions</span></span><button class="btn btn-secondary" onclick='startTopic(${JSON.stringify(t)})'>Study</button></div>`).join('')}</section>`}
function quizMenu(){app.innerHTML=`<h1>Quick Quiz</h1><section class="grid">${[10,25,50,65].map(n=>`<article class="card card-button" onclick="startQuiz(${n})"><h2>${n} Questions</h2><p>${n===65?'Complete Work Area I exam':'Randomized practice'}</p></article>`).join('')}</section>`}
const shuffled=a=>[...a].sort(()=>Math.random()-.5);window.startQuiz=n=>{activeQuiz=shuffled(bank).slice(0,Math.min(n,bank.length));currentIndex=0;answers={};renderQuestion()};window.startTopic=t=>{activeQuiz=shuffled(bank.filter(q=>q.topic===t));currentIndex=0;answers={};renderQuestion()};
function renderQuestion(){let q=activeQuiz[currentIndex],chosen=answers[q.id];app.innerHTML=`<section class="card"><div class="question-head"><span>Question ${currentIndex+1} of ${activeQuiz.length}</span><span>${q.topic}</span></div><div class="progress-track" style="margin:12px 0 20px"><div class="progress-fill" style="width:${(currentIndex+1)/activeQuiz.length*100}%"></div></div><h2>${q.q}</h2>${q.choices.map((c,i)=>`<label class="choice"><input type="radio" name="ans" value="${i}" ${chosen===i?'checked':''}><strong>${'ABCD'[i]}.</strong> ${c}</label>`).join('')}<div class="btn-row"><button class="btn btn-secondary" onclick="prevQ()" ${currentIndex===0?'disabled':''}>Previous</button><button class="btn btn-primary" onclick="${currentIndex===activeQuiz.length-1?'finishQuiz()':'nextQ()'}">${currentIndex===activeQuiz.length-1?'Submit Exam':'Next'}</button><button class="btn btn-secondary" onclick="cancelQuiz()">Exit</button></div></section>`;document.querySelectorAll('input[name=ans]').forEach(i=>i.onchange=()=>answers[q.id]=Number(i.value))}
window.nextQ=()=>{let s=$('input[name=ans]:checked');if(s)answers[activeQuiz[currentIndex].id]=+s.value;currentIndex++;renderQuestion()};window.prevQ=()=>{let s=$('input[name=ans]:checked');if(s)answers[activeQuiz[currentIndex].id]=+s.value;currentIndex--;renderQuestion()};window.cancelQuiz=()=>{activeQuiz=null;go('home')};
window.finishQuiz=()=>{let s=$('input[name=ans]:checked');if(s)answers[activeQuiz[currentIndex].id]=+s.value;let correct=0,details=activeQuiz.map(q=>{let chosen=answers[q.id],ok=chosen===q.a;if(ok)correct++;else if(!state.missed.includes(q.id))state.missed.push(q.id);return{q,chosen,ok}}),score=Math.round(correct/activeQuiz.length*100);state.attempts.push({date:new Date().toISOString(),score,correct,total:activeQuiz.length});save();app.innerHTML=`<section class="hero center"><h1>${score}%</h1><p>${correct} of ${activeQuiz.length} correct</p></section><div class="btn-row"><button class="btn btn-primary" onclick="go('home')">Home</button></div><h2>Answer Review</h2>${details.map((d,i)=>`<section class="card"><div class="question-head"><span>Question ${i+1}</span><span>${d.q.topic}</span></div><h3>${d.q.q}</h3><div class="feedback ${d.ok?'good':'bad'}"><strong>${d.ok?'Correct':'Incorrect'}</strong><br>${d.chosen===undefined?'No answer selected.<br>':`Your answer: ${'ABCD'[d.chosen]}. ${d.q.choices[d.chosen]}<br>`}Correct answer: ${'ABCD'[d.q.a]}. ${d.q.choices[d.q.a]}<br><br>${d.q.exp}</div></section>`).join('')}`;activeQuiz=null};
function missed(){let qs=state.missed.map(id=>bank.find(q=>q.id===id)).filter(Boolean);app.innerHTML=`<h1>Missed Questions</h1>${qs.length?`<button class="btn btn-primary" onclick="startMissed()">Practice Missed Questions</button>${qs.map(q=>`<section class="card"><span class="badge">${q.topic}</span><h3>${q.q}</h3><p><strong>Correct:</strong> ${'ABCD'[q.a]}. ${q.choices[q.a]}</p><p>${q.exp}</p></section>`).join('')}`:'<section class="card"><h2>Nothing here yet 🎉</h2></section>'}`};window.startMissed=()=>{activeQuiz=shuffled(state.missed.map(id=>bank.find(q=>q.id===id)).filter(Boolean));currentIndex=0;answers={};renderQuestion()};
function progress(){let a=state.attempts,avg=a.length?Math.round(a.reduce((x,y)=>x+y.score,0)/a.length):0,best=a.length?Math.max(...a.map(x=>x.score)):0;app.innerHTML=`<h1>Progress</h1><section class="grid"><article class="card"><div class="muted">Attempts</div><div class="stat">${a.length}</div></article><article class="card"><div class="muted">Average</div><div class="stat">${avg}%</div></article><article class="card"><div class="muted">Best</div><div class="stat">${best}%</div></article><article class="card"><div class="muted">Missed bank</div><div class="stat">${state.missed.length}</div></article></section>`}init();